# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: Nathan B

# Below the site title
tagline: Network / System administration blog.

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net.

# The base hostname & protocol of your site for where absolute urls are needed
url: https://nathanarkov.github.io/

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
#- text: Style Guide
#  url: /style-guide/
- text: Browse
  url: /tags/

# Author information - author info at the bottom of the post
author_name: "Nathan B"
author_bio: "My name is Nathan B. I'm a french IT student, currently on the journey to become a network and systems engineer."
author_url: "https://www.linkedin.com/in/nathan-brg/"
author_location: "Metz, France"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://justgoodthemes.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "" #"//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
#facebook_username: "username"
github_username: "NathanArkov"
#codepen_username: "username"
#dribbble_username: "username"
#medium_username: "@username"
#instagram_username: "username"
#pinterest_username: "username"
linkedin_username: "nathan-brg"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
